<a href="https://colab.research.google.com/github/khangdltUIT/CS115_Mathematics_cs/blob/main/Cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cross-validation

## Load Dataset

In [1]:
from IPython.display import clear_output

In [2]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [3]:
!cp '/content/drive/MyDrive/REPORT/Course Project/Mathematics for CS/breast_cancer_wisconsin.csv' '/content/breast_cancer_wisconsin.csv'

## Read dataset

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("/content/breast_cancer_wisconsin.csv")

In [6]:
features_name = ['radius_mean', 'texture_mean', 'perimeter_mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'area_worst', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 'concave points_worst', 'symmetry_worst', 'fractal_dimension_worst']

In [7]:
X = df[features_name]
Y = df['diagnosis']

## Import Models Machine Learning

In [15]:
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn import tree
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

## Measurance

In [ ]:
scoring = ['precision_macro', 'recall_macro', 'f1_macro']

In [12]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        pred = clf.predict(X_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")
        
    elif train==False:
        pred = clf.predict(X_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

## K-fold Cross-validation

In [ ]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn import metrics

In [ ]:
log = LogisticRegression()
sc_log = cross_val_score(log, X, Y, cv=5,scoring='f1_macro')

knn = KNeighborsClassifier(n_neighbors=4)
sc_knn = cross_val_score(knn, X, Y, cv=5,scoring='f1_macro')

linear = SVC(kernel = 'linear', C = 0.1, gamma=1)
sc_linear = cross_val_score(linear, X, Y, cv=5,scoring='f1_macro')

poly = SVC(kernel='poly')
sc_poly = cross_val_score(poly, X, Y, cv=5,scoring='f1_macro')

dtree = tree.DecisionTreeClassifier()
sc_tree = cross_val_score(dtree, X, Y, cv=5,scoring='f1_macro')

nb = GaussianNB()
sc_nb = cross_val_score(nb, X, Y, cv=5,scoring='f1_macro')

delete_log = True
if delete_log == True: clear_output()

In [ ]:
score_model = [sc_log, sc_knn, sc_linear, sc_poly, sc_tree, sc_nb]

In [ ]:
print(sc_log)

[0.92297297 0.934348   0.952129   0.93369339 0.94368771]


In [ ]:
print(sc_linear)

[0.93220627 0.94345238 0.98095556 0.91474865 0.95327876]


In [ ]:
for iscore in score_model: 
    #print(iscore.std())
    print("Mean: {}, STD: {}".format(iscore.mean().round(5), iscore.std().round(5)))

Mean: 0.93737, STD: 0.00988
Mean: 0.91449, STD: 0.02887
Mean: 0.94493, STD: 0.0221
Mean: 0.89691, STD: 0.04778
Mean: 0.9142, STD: 0.01016
Mean: 0.93334, STD: 0.01576


## Leave-one-out

In [ ]:
loo = LeaveOneOut()

In [ ]:
log = LogisticRegression()
scr_log = cross_val_score(log, X, Y, cv=loo,scoring='f1_macro')

knn = KNeighborsClassifier(n_neighbors=4)
scr_knn = cross_val_score(knn, X, Y, cv=loo,scoring='f1_macro')

linear = SVC(kernel = 'linear', C = 0.1, gamma=1)
scr_linear = cross_val_score(linear, X, Y, cv=loo,scoring='f1_macro')

poly = SVC(kernel='poly')
scr_poly = cross_val_score(poly, X, Y, cv=loo,scoring='f1_macro')

dtree = tree.DecisionTreeClassifier()
scr_tree = cross_val_score(dtree, X, Y, cv=loo,scoring='f1_macro')

nb = GaussianNB()
scr_nb = cross_val_score(nb, X, Y, cv=loo,scoring='f1_macro')

delete_log = True
if delete_log == True: clear_output()

In [ ]:
score_model_loo = [scr_log, scr_knn, scr_linear, scr_poly, scr_tree, scr_nb]

In [ ]:
for iscore in score_model_loo: 
    #print(iscore.std())
    print("Mean: {}, STD: {}".format(iscore.mean().round(5), iscore.std().round(5)))

Mean: 0.94376, STD: 0.23038
Mean: 0.92619, STD: 0.26147
Mean: 0.95255, STD: 0.2126
Mean: 0.91388, STD: 0.28054
Mean: 0.92267, STD: 0.26711
Mean: 0.93849, STD: 0.24027


## Phạt mô hình

In [10]:
xtrain, xtest, ytrain, ytest = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [26]:
log = LogisticRegression(class_weight={'B': 1.342, 'M':0.797})
log = log.fit(xtrain, ytrain)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [27]:
print_score(log, xtrain, ytrain, xtest, ytest, train = True)
print_score(log, xtrain, ytrain, xtest, ytest, train = False)

Train Result:
Accuracy Score: 93.41%
_______________________________________________
CLASSIFICATION REPORT:
                    B           M  accuracy   macro avg  weighted avg
precision    0.916667    0.972028  0.934066    0.944347      0.936743
recall       0.986207    0.842424  0.934066    0.914316      0.934066
f1-score     0.950166    0.902597  0.934066    0.926382      0.932916
support    290.000000  165.000000  0.934066  455.000000    455.000000
_______________________________________________
Confusion Matrix: 
 [[286   4]
 [ 26 139]]

Test Result:
Accuracy Score: 94.74%
_______________________________________________
CLASSIFICATION REPORT:
                   B          M  accuracy   macro avg  weighted avg
precision   0.942029   0.955556  0.947368    0.948792      0.947606
recall      0.970149   0.914894  0.947368    0.942521      0.947368
f1-score    0.955882   0.934783  0.947368    0.945332      0.947183
support    67.000000  47.000000  0.947368  114.000000    114.000000
___

In [32]:
linear = SVC(kernel = 'linear', C = 0.1, gamma=1, class_weight={'B': 1.342, 'M':0.797}) 
linear = linear.fit(xtrain, ytrain)

In [33]:
print_score(linear, xtrain, ytrain, xtest, ytest, train = True)
print_score(linear, xtrain, ytrain, xtest, ytest, train = False)

Train Result:
Accuracy Score: 96.48%
_______________________________________________
CLASSIFICATION REPORT:
                    B           M  accuracy   macro avg  weighted avg
precision    0.959732    0.974522  0.964835    0.967127      0.965095
recall       0.986207    0.927273  0.964835    0.956740      0.964835
f1-score     0.972789    0.950311  0.964835    0.961550      0.964638
support    290.000000  165.000000  0.964835  455.000000    455.000000
_______________________________________________
Confusion Matrix: 
 [[286   4]
 [ 12 153]]

Test Result:
Accuracy Score: 93.86%
_______________________________________________
CLASSIFICATION REPORT:
                   B          M  accuracy   macro avg  weighted avg
precision   0.954545   0.916667  0.938596    0.935606      0.938929
recall      0.940299   0.936170  0.938596    0.938234      0.938596
f1-score    0.947368   0.926316  0.938596    0.936842      0.938689
support    67.000000  47.000000  0.938596  114.000000    114.000000
___

In [34]:
poly = SVC(kernel = 'poly', class_weight={'B': 1.342, 'M':0.797}) 
poly = poly.fit(xtrain, ytrain)

In [35]:
print_score(poly, xtrain, ytrain, xtest, ytest, train = True)
print_score(poly, xtrain, ytrain, xtest, ytest, train = False)

Train Result:
Accuracy Score: 89.01%
_______________________________________________
CLASSIFICATION REPORT:
                    B           M  accuracy   macro avg  weighted avg
precision    0.855030    0.991453   0.89011    0.923241      0.904502
recall       0.996552    0.703030   0.89011    0.849791      0.890110
f1-score     0.920382    0.822695   0.89011    0.871539      0.884957
support    290.000000  165.000000   0.89011  455.000000    455.000000
_______________________________________________
Confusion Matrix: 
 [[289   1]
 [ 49 116]]

Test Result:
Accuracy Score: 88.60%
_______________________________________________
CLASSIFICATION REPORT:
                   B          M  accuracy   macro avg  weighted avg
precision   0.837500   1.000000  0.885965    0.918750      0.904496
recall      1.000000   0.723404  0.885965    0.861702      0.885965
f1-score    0.911565   0.839506  0.885965    0.875535      0.881856
support    67.000000  47.000000  0.885965  114.000000    114.000000
___

In [38]:
dtree = tree.DecisionTreeClassifier(class_weight={'B': 1.342, 'M':0.797})
dtree = dtree.fit(xtrain, ytrain)

In [40]:
print_score(dtree, xtrain, ytrain, xtest, ytest, train = True)
print_score(dtree, xtrain, ytrain, xtest, ytest, train = False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
               B      M  accuracy  macro avg  weighted avg
precision    1.0    1.0       1.0        1.0           1.0
recall       1.0    1.0       1.0        1.0           1.0
f1-score     1.0    1.0       1.0        1.0           1.0
support    290.0  165.0       1.0      455.0         455.0
_______________________________________________
Confusion Matrix: 
 [[290   0]
 [  0 165]]

Test Result:
Accuracy Score: 89.47%
_______________________________________________
CLASSIFICATION REPORT:
                   B          M  accuracy   macro avg  weighted avg
precision   0.923077   0.857143  0.894737    0.890110      0.895894
recall      0.895522   0.893617  0.894737    0.894570      0.894737
f1-score    0.909091   0.875000  0.894737    0.892045      0.895036
support    67.000000  47.000000  0.894737  114.000000    114.000000
_______________________________________________
Confusion

In [43]:
import numpy as np

In [44]:
from sklearn.utils.class_weight import compute_class_weight
class_weights = compute_class_weight('balanced', np.unique(Y), Y)

In [45]:
print(class_weights)

[0.79691877 1.34198113]
